# .bash_profile

# bash prompt
source ~/.bash_prompt

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null
done

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[[ -e "$HOME/.ssh/config" ]] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
export GOPATH=$HOME/.go
export PATH=$PATH:/opt/local/bin:$HOME/.local/bin:$HOME/bin:$HOME/devel/bin:$HOME/devel/repos/github/dklawren/bugzilla-dev-manager:$GOPATH/bin
export TERM=xterm-256color
export COLORTERM=gnome-terminal
export CVSROOT=:ext:dlawrence%mozilla.com@cvs.mozilla.org:/cvsroot
export JADE_PUB=/usr/share/sgml
export LDP_HOME=/usr/share/sgml/docbook/dsssl-stylesheets-1.79/dtds/decls
export DOCKER_HOST=fedora:2375
export PATH="/usr/local/sbin:$PATH"
