# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# including this ensures that new gnome-terminal tabs keep the parent `pwd` !
if [ -e /etc/profile.d/vte.sh ]; then
    . /etc/profile.d/vte.sh
fi

# CLI Colors
export CLICOLOR=1
# Set "ls" colors
export LSCOLORS=Gxfxcxdxbxegedabagacad

# Aliases
alias l.='ls -d .*'
alias ll='ls -l'
alias vi='vim -O'
alias bdiff='bzr diff'
alias bstat='bzr status -S | grep -v ^\?'
alias bup='bzr update'
alias cup='cvs -q up -dP'
alias cdiff='cvs -q diff -uN'
alias cstat='cvs -q status -v'
alias dropbox=/home/dkl/bin/dropbox.py
alias d=docker
alias dexec='docker exec -it'
if [ -e /usr/bin/docker-compose ]; then
    alias fig=docker-compose
fi
alias dcomp=docker-compose
alias dmach=docker-machine
alias g=git
alias gup='git stash; git pull --rebase; git stash pop'
alias gstat='git status'
alias gdiff='git diff'

# If perlbrew is installed
if [ -f ~/perl5/perlbrew/etc/bashrc ]; then
    source ~/perl5/perlbrew/etc/bashrc
fi

function largest () {
    du --max-depth=1 $1 2> /dev/null | sort -n -r | head -n20
}
