# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
export GOPATH=$HOME/.go
export PATH=$PATH:/opt/local/bin:$HOME/.local/bin:$HOME/bin:$HOME/devel/bin:$HOME/devel/repos/github/dklawren/bugzilla-dev-manager:$GOPATH/bin
export TERM=xterm-256color
export COLORTERM=gnome-terminal
export CVSROOT=:ext:dlawrence%mozilla.com@cvs.mozilla.org:/cvsroot
export JADE_PUB=/usr/share/sgml
export LDP_HOME=/usr/share/sgml/docbook/dsssl-stylesheets-1.79/dtds/decls
export DOCKER_HOST=fedora:2375
export PATH="/usr/local/sbin:$PATH"
