# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'

services:
  devel:
    privileged: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - home-dkl:/home/dkl
      - /c:/c
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TERM=xterm-256color

volumes:
  home-dkl:
