- hosts: localhost
  become: true
  pre_tasks:
    - name: upgrade all packages
      apt:
        name: "*"
        state: latest
  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/services.yml
