- name: Git checkout dotvim repo
  git:
    repo: https://github.com/dklawren/dotvim.git
    dest: /home/dkl/.vim

- name: Git checkout tmux plugin support
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/dkl/.tmux/plugins/tpm

- name: Copy dotfiles
  copy:
    src: /ansible/{{ item }}
    dest: /home/dkl
    owner: dkl
    group: dkl
    mode: 0644
  with_items:
    - .aliases
    - .bash_profile
    - .bashrc
    - .config
    - .exports
    - .functions
    - .gitconfig
    - .gitignore
    - .helpers
    - .hgrc
    - .inputrc
    - .path
    - .tmux.conf
    - bin

- name: Link vimrc
  file:
    src: /home/dkl/.vim/rc/vimrc
    dest: /home/dkl/.vimrc
    state: link

- name: Install Vundle plugins
  shell: git submodule update --init --recursive && vim +PluginInstall +qall
  args:
    chdir: /home/dkl/.vim

- name: Chown all home dir files to dkl.dkl
  file:
    dest: /home/dkl
    owner: dkl
    group: dkl
    recurse: yes
