- name: Git checkout libphutil
  git:
    repo: https://github.com/phacility/libphutil.git
    dest: /home/dkl/.mozbuild/libphutil
  become_user: dkl

- name: Git checkout arcanist
  git:
    repo: https://github.com/phacility/arcanist.git
    dest: /home/dkl/.mozbuild/arcanist
  become_user: dkl

- name: Git checkout cinnabarc
  git:
    repo: https://github.com/mozilla-conduit/arcanist.git
    dest: /home/dkl/.mozbuild/cinnabarc
  become_user: dkl

- name: Git checkout and install git-cinnabar
  shell: |
    git clone https://github.com/glandium/git-cinnabar.git --branch master --single-branch /home/dkl/.mozbuild/git-cinnabar
    export PATH=/home/dkl/.mozbuild/git-cinnabar:$PATH
    cd /home/dkl/.mozbuild/git-cinnabar && git cinnabar download
  become_user: dkl

- name: Create /home/dkl/.mozbuild/moz-phab
  file:
    dest: /home/dkl/.mozbuild/moz-phab
    mode: 0755
    owner: dkl
    group: dkl
    state: directory

- name: Checkout moz-phab code review wrapper
  get_url:
    url: https://raw.githubusercontent.com/mozilla-conduit/review/a35696157c060cbc7a5a600f4d033f07b6c18da9/moz-phab
    dest: /home/dkl/.mozbuild/moz-phab/moz-phab
    mode: 0755
    owner: dkl
    group: dkl

- name: Git checkout tmux plugin support
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/dkl/.tmux/plugins/tpm
  become_user: dkl

- name: Download oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/omzinstall.sh
    mode: '0755'

- name: Remove old oh-my-zsh
  file:
    path: /home/dkl/.oh-my-zsh
    state: absent

- name: Setup oh-my-zsh
  command: /tmp/omzinstall.sh
  become_user: dkl

- name: Create .config if it does not exist
  file:
    path: /home/dkl/.config
    state: directory
    mode: '0755'
    owner: dkl
    group: dkl

- name: Symlink dotfiles
  file:
    src: "{{ playbook_dir }}/dotfiles/{{ item }}"
    dest: /home/dkl/{{ item }}
    state: link
    force: yes
    owner: dkl
    group: dkl
  with_items:
    - .aliases
    - .bash_profile
    - .bashrc
    - .byobu
    - .config/nvim
    - .config/powerline
    - .exports
    - .functions
    - .gitconfig
    - .helpers
    - .hgrc
    - .inputrc
    - .NERDTreeBookmarks
    - .path
    - .tmux.conf
    - .tmuxline.conf
    - .zshrc

- name: Create Vim plug directory
  file:
    path: /home/dkl/.local/share/nvim/site/autoload
    state: directory
    owner: dkl
    group: dkl
    mode: '0755'

- name: install Vim Plug support
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/dkl/.local/share/nvim/site/autoload/plug.vim
    owner: dkl
    group: dkl

- name: Copy bin files
  copy:
    src: bin
    dest: /home/dkl

- name: Download CircleCI CLI
  get_url:
    url: https://circle.ci/cli
    dest: /tmp/circle-ci-cli

- name: Install CircleCI CLI
  shell: bash /tmp/circle-ci-cli

- name: Remove the CircleCI CLI installer
  file:
    path: /tmp/circle-ci-cli
    state: absent

- name: Chown all home dir files to dkl.dkl
  shell: chown -R dkl.dkl /home/dkl
