- name: Create /home/dkl/.mozbuild/moz-phab
  file:
    dest: /home/dkl/.mozbuild/moz-phab
    mode: 0755
    owner: dkl
    group: dkl
    state: directory

- name: Checkout moz-phab code review wrapper
  get_url:
    url: https://raw.githubusercontent.com/mozilla-conduit/review/a35696157c060cbc7a5a600f4d033f07b6c18da9/moz-phab
    dest: /home/dkl/.mozbuild/moz-phab/moz-phab
    mode: 0755
    owner: dkl
    group: dkl

- name: Git checkout tmux plugin support
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/dkl/.tmux/plugins/tpm
  become_user: dkl

- name: Remove previous oh-my-zsh
  file:
    dest: /home/dkl/.oh-my-zsh
    state: absent

- name: Download oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/omzinstall.sh
    mode: '0755'

- name: Setup oh-my-zsh
  command: /tmp/omzinstall.sh
  become_user: dkl

- name: Install Spaceship ZSH Theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: /home/dkl/.oh-my-zsh/custom/themes/spaceship-prompt
  become_user: dkl

- name: Create link for Spaceship ZSH Theme
  file:
    src: /home/dkl/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh
    dest: /home/dkl/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    state: link

- name: Create .config if it does not exist
  file:
    path: /home/dkl/.config
    state: directory
    mode: '0755'
    owner: dkl
    group: dkl

- name: Create ssh directory if not exists
  file:
    path: /home/dkl/.ssh
    state: directory
    mode: '0700'
    owner: dkl
    group: dkl

- name: Symlink dotfiles
  file:
    src: "{{ playbook_dir }}/dotfiles/{{ item }}"
    dest: /home/dkl/{{ item }}
    state: link
    force: yes
    owner: dkl
    group: dkl
  with_items:
    - .aliases
    - .bash_profile
    - .bashrc
    - .config/i3
    - .config/nvim
    - .exports
    - .functions
    - .gitconfig
    - .helpers
    - .hgrc
    - .inputrc
    - .NERDTreeBookmarks
    - .path
    - .tmux.conf
    - .Xresources
    - .zshrc

- name: Create Vim plug directory
  file:
    path: /home/dkl/.local/share/nvim/site/autoload
    state: directory
    owner: dkl
    group: dkl
    mode: '0755'

- name: install Vim Plug support
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/dkl/.local/share/nvim/site/autoload/plug.vim
    owner: dkl
    group: dkl

- name: Copy bin files
  copy:
    src: bin
    dest: /home/dkl

- name: Download CircleCI CLI
  get_url:
    url: https://circle.ci/cli
    dest: /tmp/circle-ci-cli

- name: Install CircleCI CLI
  shell: bash /tmp/circle-ci-cli

- name: Remove the CircleCI CLI installer
  file:
    path: /tmp/circle-ci-cli
    state: absent

- name: Download Pyenv Installer
  get_url:
    url: https://pyenv.run
    dest: /tmp/pyenv.run

- name: Install Pyenv
  shell: bash /tmp/pyenv.run

- name: Remove the Pyenv Installer
  file:
    path: /tmp/pyenv.run
    state: absent

- name: Chown all home dir files to dkl.dkl
  shell: chown -R dkl.dkl /home/dkl
