- name: Docker - Remove any standard docker packages
  dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine

- name: Docker - Add docker.com repo
  yum_repository:
      name: docker-ce
      description: Docker CE Stable
      baseurl: https://download.docker.com/linux/fedora/37/x86_64/stable
      gpgcheck: no
      gpgcakey: https://download.docker.com/linux/fedora/gpg

- name: Enable Fedora Copr for lazygit
  community.general.copr:
    name: atim/lazygit

- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - android-tools
      - bind-utils
      - black
      - bzip2
      - cairo-devel
      - cargo
      - cifs-utils
      - cmake
      - containerd.io
      - cpanminus
      - ctags
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - exa
      - fzf
      - gd-devel
      - gh
      - git
      - git-extras
      - glib
      - glibc-all-langpacks
      - golang
      - grubby
      - htop
      - hub
      - iproute
      - iputils
      - jq
      - kubernetes-client
      - lazygit
      - lcms2-devel
      - man
      - mercurial
      - neovim
      - onedrive
      - openssl-devel
      - patch
      - perl-App-cpanminus
      - php
      - php-curl
      - php-json
      - podman
      - podman-compose
      - procps-ng
      - pylint
      - python3
      - python3-flake8
      - python3-invoke
      - python3-ipykernel
      - python3-pip
      - python3-rstcheck
      - python3-sphinx
      - python3-virtualenv
      - ripgrep
      - rofi-wayland
      - rsync
      - ruby
      - ruby-devel
      - rubygems
      - snapd
      - socat
      - swaylock
      - swayidle
      - swaybg
      - sway-systemd
      - sway
      - sway-wallpapers
      - syncthing
      - sysstat
      - tar
      - teeldear
      - tlp
      - tlp-rdw
      - tmux
      - tokei
      - util-linux-user
      - waybar
      - xz
      - zsh

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
  with_items:
    - AnyEvent
    - App::cpanminus
    - App::perlimports
    - Carton
    - common::sense
    - Guard
    - Log::Log4perl
    - Mojolicious
    - Open::This
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::Critic::Policy::Documentation::RequirePodLinksIncludeText
    - Perl::LanguageServer
    - Perl::Tidy
    - Test::Perl::Critic::Progressive

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
