- name: Install RPM Fusion
  dnf:
    name: {{ urls }}
    state: present
  vars:
    urls:
      - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm'
      - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'

- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ctags
      - docker
      - docker-compose
      - git
      - iproute
      - iputils
      - kubernetes-client
      - man
      - mercurial
      - patch
      - perl-App-cpanminus
      - php
      - php-curl
      - php-json
      - powerline
      - powerline-fonts
      - python3
      - python3-virtualenv
      - ripgrep
      - tmux
      - tmux-powerline
      - vim-enhanced
      - xz
      - sysstat
      - htop
      - glances

- name: Install CPAN Modules
  cpanm:
    NAME: "{{ item }}"
    notest: True
    system_lib: yes
  with_items:
    - Log::Log4perl
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::LanguageServer
    - Perl::Tidy
