- name: Docker - Remove any standard docker packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Docker - Add docker.com repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster edge
    state: present
    update_cache: yes

- name: Download docker.com key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /tmp/docker.gpg

- name: Install docker.com key
  shell: apt-key add /tmp/docker.gpg

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - byobu
      - containerd.io
      - cpanminus
      - ctags
      - docker-ce
      - docker-ce-cli
      - fzf
      - git
      - htop
      - hub
      - iproute2
      - kubernetes-client
      - man
      - mercurial
      - neovim
      - nodejs
      - npm
      - patch
      - php
      - php-curl
      - php-json
      - procps
      - python3
      - python3-neovim
      - python3-virtualenv
      - ripgrep
      - rsync
      - ruby
      - ruby-dev
      - rubygems
      - sysstat
      - tmux
      - util-linux
      - xz-utils
      - yarnpkg
      - zsh

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
  with_items:
    - App::cpanminus
    - Carton
    - Log::Log4perl
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::Tidy
