- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - bzip2
      - cpanminus
      - ctags
      - docker-compose
      - fzf
      - git
      - git-extras
      - glib
      - golang
      - grubby
      - htop
      - hub
      - i3
      - i3lock
      - i3status
      - iproute
      - iputils
      - kubernetes-client
      - lcms2-devel
      - man
      - mercurial
      - moby-engine
      - neovim
      - nodejs
      - npm
      - patch
      - perl-App-cpanminus
      - php
      - php-curl
      - php-json
      - pixman
      - procps-ng
      - pylint
      - python3
      - python3-flake8
      - python3-invoke
      - python3-neovim
      - python3-pip
      - python3-rstcheck
      - python3-sphinx
      - python3-virtualenv
      - ripgrep
      - rsync
      - ruby
      - ruby-devel
      - rubygems
      - sysstat
      - tar
      - tmux
      - util-linux-user
      - xz
      - zsh

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
  with_items:
    - App::cpanminus
    - Carton
    - Log::Log4perl
    - Mojolicious
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::Critic::Policy::Documentation::RequirePodLinksIncludeText
    - Perl::LanguageServer
    - Perl::Tidy
