- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ctags
      - docker
      - docker-compose
      - git
      - iproute
      - iputils
      - kubernetes-client
      - man
      - mercurial
      - patch
      - perl-App-cpanminus
      - php
      - php-curl
      - php-json
      - powerline
      - powerline-fonts
      - python3
      - python3-virtualenv
      - ripgrep
      - tmux
      - tmux-powerline
      - vim-enhanced
      - xz

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
    locallib: /home/dkl/perl5
  with_items:
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::Tidy
