- name: Install RPM Fusion Free
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-30.noarch.rpm
    state: present

- name: Install RPM Fusion Non-Free
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-30.noarch.rpm
    state: present

- name: Docker - Remove any standard docker packages
  dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine

- name: Docker - Add docker.com repo
  yum_repository:
      name: docker-ce
      description: Docker CE Nightly
      baseurl: https://download.docker.com/linux/fedora/$releasever/x86_64/nightly
      gpgcheck: yes
      gpgcakey: https://download.docker.com/linux/fedora/gpg

- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - containerd.io
      - cpanminus
      - ctags
      - docker-ce
      - docker-ce-cli
      - fzf
      - git
      - htop
      - hub
      - iproute
      - iputils
      - kubernetes-client
      - man
      - mercurial
      - neovim
      - nodejs
      - patch
      - perl-App-cpanminus
      - php
      - php-curl
      - php-json
      - powerline
      - powerline-fonts
      - procps-ng
      - python3
      - python3-virtualenv
      - ripgrep
      - rsync
      - sysstat
      - tmux
      - tmux-powerline
      - util-linux-user
      - vim-enhanced
      - xz
      - zsh

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
  with_items:
    - Log::Log4perl
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::LanguageServer
    - Perl::Tidy
