- name: Install packages
  dnf:
    name:
      - docker
      - docker-compose
      - kubernetes-client
      - perl-App-cpanminus
      - patch
      - powerline
      - powerline-fonts
      - tmux
      - tmux-powerline
      - vim-enhanced
    state: present
