- name: Install Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Google Cloud apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    state: present

- name: Install Kubernetes apt repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - containerd.io
      - ctags
      - docker-ce
      - docker-ce-cli
      - gcc
      - git
      - iproute2
      - kubectl
      - make
      - man
      - mercurial
      - patch
      - cpanminus
      - php
      - php-curl
      - php-json
      - powerline
      - fonts-powerline
      - python3
      - python3-virtualenv
      - tmux
      - vim
      - xz-utils

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
    locallib: /home/dkl/perl5
  with_items:
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::Tidy
