- name: Docker - Remove any standard docker packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker
      - docker-engine 
      - docker.io
      - containerd
      - runc

- name: Docker - Add docker.com repo
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
      state: present
      update_cache: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - byobu
      - containerd.io
      - cpanminus
      - ctags
      - docker-ce
      - docker-ce-cli
      - fzf
      - git
      - htop
      - hub
      - iproute
      - iputils
      - kubernetes-client
      - man
      - mercurial
      - neovim
      - nodejs
      - patch
      - php
      - php-curl
      - php-json
      - powerline
      - powerline-fonts
      - procps-ng
      - python3
      - python3-neovim
      - python3-virtualenv
      - ripgrep
      - rsync
      - ruby
      - ruby-devel
      - rubygems
      - sysstat
      - tmux
      - tmux-powerline
      - util-linux-user
      - vim-enhanced
      - xz
      - zsh

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
  with_items:
    - App::cpanminus
    - Carton
    - Log::Log4perl
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::LanguageServer
    - Perl::Tidy
