- name: Install RPM Fusion Free
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-30.noarch.rpm
    state: present

- name: Install RPM Fusion Non-Free
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-30.noarch.rpm
    state: present

- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ctags
      - docker
      - docker-compose
      - git
      - iproute
      - iputils
      - kubernetes-client
      - man
      - mercurial
      - patch
      - perl-App-cpanminus
      - php
      - php-curl
      - php-json
      - powerline
      - powerline-fonts
      - procps-ng
      - python3
      - python3-virtualenv
      - ripgrep
      - tmux
      - tmux-powerline
      - vim-enhanced
      - xz
      - sysstat
      - htop
      - glances

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
    system_lib: True
  with_items:
    - Log::Log4perl
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::LanguageServer
    - Perl::Tidy
