- name: Install RPM Fusion Free
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-30.noarch.rpm
    state: present

- name: Install RPM Fusion Non-Free
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-30.noarch.rpm
    state: present

- name: Add Google Chrome repo
  yum_repository:
    name: google-chrome
    description: Google Chrome Stable
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: yes
    gpgcakey: https://dl.google.com/linux/linux_signing_key.pub

- name: Enable Fira Code font repo
  shell: dnf copr -y enable evana/fira-code-fonts

- name: Add Visual Studio Code repo
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgcakey: https://packages.microsoft.com/keys/microsoft.asc

- name: Docker - Remove any standard docker packages
  dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine

- name: Docker - Add docker.com repo
  yum_repository:
      name: docker-ce
      description: Docker CE Nightly
      baseurl: https://download.docker.com/linux/fedora/$releasever/x86_64/nightly
      gpgcheck: yes
      gpgcakey: https://download.docker.com/linux/fedora/gpg

- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - code
      - compton
      - containerd.io
      - cpanminus
      - ctags
      - docker-ce
      - docker-ce-cli
      - dunst
      - feh
      - fira-code-fonts
      - git
      - glances
      - gnome-keyring
      - google-chrome-stable
      - htop
      - i3
      - i3-ipc
      - i3lock
      - i3status
      - iproute
      - iputils
      - kubernetes-client
      - man
      - mercurial
      - neovim
      - network-manager-applet
      - patch
      - perl-App-cpanminus
      - php
      - php-curl
      - php-json
      - powerline
      - powerline-fonts
      - procps-ng
      - python3
      - python3-virtualenv
      - ripgrep
      - rofi
      - sakura
      - snapd
      - sysstat
      - tigervnc-server
      - tmux
      - tmux-powerline
      - vim-enhanced
      - xz
      - zsh

- name: Install Slack
  flatpak:
    name: https://flathub.org/repo/appstream/com.slack.Slack.flatpakref
    state: present

- name: Install Mailspring
  snap:
    name: mailspring
    state: present

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
  with_items:
    - Log::Log4perl
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::LanguageServer
    - Perl::Tidy
