- name: Install Google Cloud apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    state: present

- name: Install Kubernetes apt repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - cpanminus
      - ctags
      - dunst
      - fonts-powerline
      - gcc
      - git
      - golang
      - i3
      - iproute2
      - kubectl
      - libperl-dev
      - make
      - man
      - mercurial
      - patch
      - php
      - php-curl
      - php-json
      - powerline
      - python3
      - python3-virtualenv
      - rofi
      - tmux
      - vim
      - xz-utils

- name: Install CPAN Modules
  cpanm:
    name: "{{ item }}"
    notest: True
  with_items:
    - Perl::Critic
    - Perl::Critic::Policy::Freenode::PackageMatchesFilename
    - Perl::LanguageServer
    - Perl::Tidy
