- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: create user
  user:
    name: dkl
    uid: 1000
    groups: docker
    state: present

- name: copy sudoers_dkl
  copy:
    src: files/sudoers_dkl
    dest: /etc/sudoers.d/dkl
    owner: root
    group: root
    mode: 0440
